randomize();
global.gamePaused = false;
global.textspeed = .75;
global.targetRoom = -1;
global.targetX = -1;
global.targetY = -1;
global.targetdirection = 0;
global.iLifted = noone;
global.icamera = instance_create_layer(0,0,layer,o_camera);
surface_resize(application_surface,RESOLUTION_W,RESOLUTION_H);
room_goto(ROOM_START);
